name: agentgames
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.0.5
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - comm=0.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.6.3
  - ipykernel=6.29.5
  - ipython=8.27.0
  - jedi=0.19.1
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.15
  - parso=0.8.3
  - pexpect=4.8.0
  - pip=24.2
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - python=3.12.7
  - python-dateutil=2.9.0post0
  - readline=8.2
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - wcwidth=0.2.5
  - wheel=0.44.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
    - aiohappyeyeballs==2.4.3
    - aiohttp==3.11.7
    - aiosignal==1.3.1
    - annotated-types==0.7.0
    - anyio==4.6.2.post1
    - attrs==24.2.0
    - bleach==6.2.0
    - certifi==2024.8.30
    - charset-normalizer==3.4.0
    - click==8.1.7
    - cloudpickle==3.1.0
    - compressed-tensors==0.8.0
    - datasets==3.1.0
    - dill==0.3.8
    - diskcache==5.6.3
    - distro==1.9.0
    - dnspython==2.7.0
    - einops==0.8.0
    - email-validator==2.2.0
    - fastapi==0.115.5
    - fastapi-cli==0.0.5
    - filelock==3.16.1
    - frozenlist==1.5.0
    - fsspec==2024.9.0
    - gguf==0.10.0
    - greenlet==3.1.1
    - h11==0.14.0
    - httpcore==1.0.7
    - httptools==0.6.4
    - httpx==0.27.2
    - huggingface-hub==0.26.2
    - idna==3.10
    - importlib-metadata==8.5.0
    - interegular==0.3.3
    - jinja2==3.1.4
    - jiter==0.7.1
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - kaggle==1.6.17
    - lark==1.2.2
    - llvmlite==0.43.0
    - lm-format-enforcer==0.10.9
    - markdown-it-py==3.0.0
    - markupsafe==3.0.2
    - mdurl==0.1.2
    - mistral-common==1.5.1
    - mpmath==1.3.0
    - msgpack==1.1.0
    - msgspec==0.18.6
    - multidict==6.1.0
    - multiprocess==0.70.16
    - networkx==3.4.2
    - numba==0.60.0
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-ml-py==12.560.30
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127
    - openai==1.55.0
    - opencv-python-headless==4.10.0.84
    - outlines==0.0.46
    - packaging==24.2
    - pandas==2.2.3
    - partial-json-parser==0.2.1.1.post4
    - pillow==10.4.0
    - prometheus-client==0.21.0
    - prometheus-fastapi-instrumentator==7.0.0
    - propcache==0.2.0
    - protobuf==5.28.3
    - psutil==6.1.0
    - psycopg2-binary==2.9.10
    - py-cpuinfo==9.0.0
    - pyairports==2.1.1
    - pyarrow==18.0.0
    - pycountry==24.6.1
    - pydantic==2.10.1
    - pydantic-core==2.27.1
    - pygments==2.18.0
    - python-dotenv==1.0.1
    - python-multipart==0.0.17
    - python-slugify==8.0.4
    - pytz==2024.2
    - pyyaml==6.0.2
    - pyzmq==26.2.0
    - ray==2.39.0
    - referencing==0.35.1
    - regex==2024.11.6
    - requests==2.32.3
    - rich==13.9.4
    - rpds-py==0.21.0
    - safetensors==0.4.5
    - sentencepiece==0.2.0
    - shellingham==1.5.4
    - sniffio==1.3.1
    - sqlalchemy==2.0.36
    - starlette==0.41.3
    - sympy==1.13.1
    - text-unidecode==1.3
    - tiktoken==0.7.0
    - tokenizers==0.20.3
    - torch==2.5.1
    - torchvision==0.20.1
    - tqdm==4.67.0
    - transformers==4.46.3
    - triton==3.1.0
    - typer==0.13.1
    - typing-extensions==4.12.2
    - tzdata==2024.2
    - urllib3==2.2.3
    - uvicorn==0.32.1
    - uvloop==0.21.0
    - vllm==0.6.4.post1
    - watchfiles==0.24.0
    - webencodings==0.5.1
    - websockets==14.1
    - xformers==0.0.28.post3
    - xxhash==3.5.0
    - yarl==1.18.0
    - zipp==3.21.0
